### ISSUE TITLE
https://<wilmapath>/index_json returns 403 once logged in

### ISSUE THREAD

**Issue by Esinko** [developerfromjokela/wilma_api#1]
The "homepage" data is unavailable on some Wilma servers and a note of it returning common-403 (permission denied error) when it's unavailable should be in the wiki.

**Comment by developerfromjokela** [comment]
The 403 occurs when logging in without that API key. APIs in documentation works only when logged in with the api.

I can make another repo focusing on APIs without API key.

**Comment by Esinko** [comment]
Yes but this happens when you are logged in. When not logged in a failed login result is given

**Comment by developerfromjokela** [comment]
Did you include the API key? Usually 403 error means failed login or disabled API

**Comment by Esinko** [comment]
The api is disabled then?

**Comment by Esinko** [comment]
Because I did include the key

**Comment by developerfromjokela** [comment]
I'll add a note that failed error is 403.

**Comment by developerfromjokela** [comment]
> Because I did include the key

Just verifying, your key is a SHA1 hash, (wiki has a guide how to generate) right?

**Comment by Esinko** [comment]
Everything is correct but again the data is for some reason found elsewhere. The data is found in /overview

**Comment by developerfromjokela** [comment]
It was my fault. The apikey was documented wrong. `ApiKey` value should be as following: `sha1:<HASH_ITSELF>`.

I've corrected the wiki.

**Comment by developerfromjokela** [comment]
Let me know if it works after adding sha1: to the value

**Comment by Esinko** [comment]
No. Still no luck

**Comment by Esinko** [comment]
These are all issues with permissions. It should give a permission denied because of the user account permissions and not just a common 403 error. This will be resolved when it's noted that a common-403 can also mean that the account does not have the required permissions to make that request.

**Comment by developerfromjokela** [comment]
> No. Still no luck

Can you post your login post content and url where you're making that login request?
