### ISSUE TITLE
https://<wilmapath>/messages/index_json returns 403 error

### ISSUE THREAD

**Issue by Esinko** [developerfromjokela/wilma_api#2]
The url in the title gives the common-403 error on some Wilma servers while the json data is actually available in https://\<wilmpath>/messages/list or https://\<wilmapath>/messages/list/index.json
The wiki should include a note about this possible URL difference between Wilma servers

**Comment by Esinko** [comment]
In short: The index_json in the url can sometimes be "list" instead

**Comment by developerfromjokela** [comment]
The 403 occurs when logging in without that API key. APIs in documentation works only when logged in with the api.

I can make another repo focusing on APIs without API key.

**Comment by developerfromjokela** [comment]
It works also when i.e. when logging via other services to Wilma, API is turned on. Basic login with the browser should not activate the API afaik.

**Comment by Esinko** [comment]
That's not the issue. The issue is that the data you'd expect to be in .../index_json is on some servers in .../list

**Comment by developerfromjokela** [comment]
Is there version differences with different servers?

**Comment by Esinko** [comment]
From what I know once the backend of wilma is setup it will never be updated unless the owners specifically order an update, which they don't do.
So the servers' versions almost never match

**Comment by Esinko** [comment]
So yes. The versions can be different and often are

**Comment by developerfromjokela** [comment]
> That's not the issue. The issue is that the data you'd expect to be in .../index_json is on some servers in .../list

For me this sounds like an disabled API.
I am not sure, you can be right. Maybe it really is in ../list instead of ../index_json

I haven't seen a Wilma Server giving 403 if the API isn't disabled.

**Comment by developerfromjokela** [comment]
> From what I know once the backend of wilma is setup it will never be updated unless the owners specifically order an update, which they don't do.
> So the servers' versions almost never match

Can you tell me the server version number where it's ../list instead of ../index_json? I'll add that to the documentation

**Comment by Esinko** [comment]
Where can I find that?

**Comment by developerfromjokela** [comment]
The `/index_json` should give you `ApiVersion`

On Wilma login screen in browser, version number is present:
![kuva](https://user-images.githubusercontent.com/40487414/90265355-23121800-de5b-11ea-84f2-fd3100ccc537.png)

**Comment by Esinko** [comment]
Oh yeah I did not think about that

**Comment by Esinko** [comment]
Same version, but I've never trusted that number

**Comment by developerfromjokela** [comment]
Then it should work. 
I have `ApiVersion` 11, and ../messages/index_json and ../messages/list both work.

**Comment by Esinko** [comment]
Well for me only ../messages/list work. Which makes no sense, but that's not a surprise.

**Comment by Esinko** [comment]
These are all issues with permissions. It should give a permission denied because of the user account permissions and not just a common 403 error. This will be resolved when it's noted that a common-403 can also mean that the account does not have the required permissions to make that request.
