### ISSUE TITLE
No docs of /api/v<version_nro>/

### ISSUE THREAD

**Issue by Esinko** [developerfromjokela/wilma_api#3]
There is no documentation of the "real" Wilma api. Please look into documenting it.
Known paths:
/api/v1/schools/
/api/v1/students
/api/v1/classes

**Comment by developerfromjokela** [comment]
Yes I know about this API, haven't documented yet. Thanks for asking

**Comment by developerfromjokela** [comment]
In fact, `/api/v1/schools/` has another API that does the same thing, `/profiles/index_json`.
