### ISSUE TITLE
What is "the api key"

### ISSUE THREAD

**Issue by Esinko** [developerfromjokela/wilma_api#4]
What does this mean exactly:
"ApiKey - Value: sha1:<HASH_VALUE>,How to get <HASH_VALUE>: Generate a SHA1 key using this example: (||<API_KEY>). is the username,you are familiar with, now<API_KEY>` is a weird one. You can't get it easily. Only ways is to send a request to Visma (if no one answers, write directly to the CEO and magic will happen), or (little bit illegal) go and extract it from their app"
Could you explain this in some more detail?
Also how does the webclient make requests if the "apikey" is never included... (I checked the form that makes the request)

**Comment by developerfromjokela** [comment]
This means that Visma restricts access to their API (most of them, there are unrestricted ones) using API Keys.

Value of ApiKey: sha1:<HASH_VALUE>

<HASH_VALUE> is a SHA1 hash. The content is in that Wiki.

The <API_KEY> is the API key that visma gives you. Without that login fails. 

This API key can be obtained by contacting visma support. If they don't answer in a month (i.e. that was my case), I'd contact to the CEO of Visma Enterprise Oy (company responsible for Wilma), and shortly after I got an answer from Visma support.

When I was reverse engineering Wilma app, I found it really easy to find the API key. It's just an constant named APIKEY, not so hard to search that.

 I don't recommend using this as this may get you in legal trouble. Better to sign one agreement with Visma and sleep well than fearing lawsuit from Visma 🙂.

If something is still confusing, questions are welcome.

**Comment by Esinko** [comment]
Where is this "api key" used usually? I've never encountered a need to include an api token so far.

**Comment by developerfromjokela** [comment]
In the login. It's used only in login, in documentation called POST Authentication.

When API key is included, it enabled Wilma API and stores that setting in the session cookie.

**Comment by developerfromjokela** [comment]
> Where is this "api key" used usually? I've never encountered a need to include an api token so far.

This can be easily seen if you i.e. intercept Wilma app network traffic.

**Comment by Esinko** [comment]
What features does the api key enable that are otherwise disabled?

**Comment by developerfromjokela** [comment]
i.e. schedule, announcements, lesson notes etc. As JSON.

**Comment by developerfromjokela** [comment]
Schedule is documented in wiki

**Comment by developerfromjokela** [comment]
And exams can be fetched as JSON. 

For teachers you can edit students lesson notes with API. That's disabled normally, enabled when using API key.

**Comment by Esinko** [comment]
So If I want API access who should I contact and what do I need to sign

**Comment by developerfromjokela** [comment]
And there are a lot of json API requests not available by default.

I've seen them enabled if you authorize to Wilma from another service.

**Comment by Esinko** [comment]
> So If I want API access who should I contact and what do I need to sign

**Comment by developerfromjokela** [comment]
> So If I want API access who should I contact and what do I need to sign

You should contact Visma. I can give you contact details in a moment.

There's an agreement that says basically following:

- If you make a suggestion to Visma about their API and they get more profit because of your suggestion, you can't get any money from that idea. If you suggest i.e. make something better, and for some reason someone decided to pay (for what? I am confused too) something, you can't demand any money for your idea/suggestion.

- if you feel like API key is "stolen", contact immediately to Visma and report it as stolen

- If any of your services that you built on Visma API causes an security issue and damage, you're responsible for it

**Comment by developerfromjokela** [comment]
Here's link to their contact page: 
https://www.visma.fi/inschool/wilma/

There is a contact form, and some contact persons. Hope this would help.

When I was submitting emails, I got no answer in a month, so I contacted via email to the CEO, because there weren't much people left to contact. 

After I wrote an email to CEO, I got response within few days.

But overall from that first email to receiving the API key it took almost a year. About 9-10 months if I remember correctly. 

They were "writing the agreement", about 6 months :open_mouth:.

**Comment by ahnl** [comment]
Alternatively there is a way to log in and access **everything you can imagine of** (no keys, but no API either) :neckbeard: :

1. Parse the HTML of the `/` and extract SESSIONID form input.
2. Send a POST request to `/login` with the needed form fields (including your SESSIONID).
3. You're inside. Go ahead and parse any page you need using an HTML parser and extract values you need for your application.

**Comment by developerfromjokela** [comment]
Yes, that works. In fact even with the API there's a lot of stuff that doesn't have APIs. One real advantage in APIs is that Visma would (I hope so) inform you of any upcoming changes to the API.

**Comment by developerfromjokela** [comment]
@ahnl you can get the Session ID with /index_json. It gives you the Session ID without any keys.

**Comment by developerfromjokela** [comment]
@ahnl I think API client library without any keys and stuff would be great. I think it deserves another repo :grinning:

**Comment by developerfromjokela** [comment]
We can create a new github account just for this one purpose, creating API-key free Wilma client libraries. This opens new possibilities to build projects for Wilma.

**Comment by ahnl** [comment]
> @ahnl I think API client library without any keys and stuff would be great. I think it deserves another repo 😀

It sure would deserve a repo. I'll contact you soon for further discussions.

**Comment by Esinko** [comment]
Just make a new github org. It's way easier like that

**Comment by Esinko** [comment]
About the parsing the html, I already do that. The html even has tags on where the data starts and ends, so parsing is super easy.

**Comment by Esinko** [comment]
I can write an "api-less" Wilma package for Node.Js I'm already pretty far in my own project so I can just modify that

**Comment by ahnl** [comment]
> I can write an "api-less" Wilma package for Node.Js I'm already pretty far in my own project so I can just modify that

I have been working with Wilma and Node.JS before, too! I personally have used Cheerio to parse HTML and extract values I need. 

I'll add you to the organization.

**Comment by Esinko** [comment]
Great! Guess we can get it done quickly then. I'll join the org
