### ISSUE TITLE
Sources of this data?

### ISSUE THREAD

**Issue by Esinko** [developerfromjokela/wilma_api#6]
What are the sources for this documentation? Are the requests fully reverse-engineered?

**Comment by developerfromjokela** [comment]
Part of this is from Visma's documentation 10%, rest of them reverse-engineered. 

This was the reason to make this documentation. Visma's own documentation doesn't contain all necessary information needed.

**Comment by developerfromjokela** [comment]
I started reverse engineering before Visma sent me their documentation.

**Comment by Esinko** [comment]
Alright
