### ISSUE TITLE
Add to the Wiki "Overview"

### ISSUE THREAD

**Issue by jaakop** [developerfromjokela/wilma_api#8]
A get request to
https://<your_wilma_server>/overview
holds a lot of information, once logged in.
This could be useful if added to the wiki.

**Comment by developerfromjokela** [comment]
Thanks! We're actually building new documentation (and libraries) for API keyless API. This documentation is meant for these who has API key.  

Here's a link to Open Wilma organization: [https://github.com/OpenWilma](https://github.com/OpenWilma)

**Comment by developerfromjokela** [comment]
This repo ([https://github.com/OpenWilma/parsing](https://github.com/OpenWilma/parsing)) has documentation how to parse JSON and HTML to get useful information out of Wilma.
